[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
arrow = "53.2.0"
clap = {version ="4.5.21", features =["derive"]}
parquet = "53.2.0"
rayon = "1.10.0"
serde_json = "1.0.132"
flate2 = "1.0"
indicatif = "0.17.9"
